# python plex_meta_manager.py -r
libraries:
  Anime:
    metadata_path:
    - url: https://raw.githubusercontent.com/housefisharr/PMM-Configs/main/anime-charts.yml
    - url: https://raw.githubusercontent.com/housefisharr/PMM-Configs/main/collections-franchises.yml
  Movies:
    metadata_path:
    - url: https://raw.githubusercontent.com/housefisharr/PMM-Configs/main/movie-awards.yml
    - url: https://raw.githubusercontent.com/housefisharr/PMM-Configs/main/movie-charts.yml
    - url: https://raw.githubusercontent.com/housefisharr/PMM-Configs/main/collections-franchises.yml
  TV Shows:
    metadata_path:
    - url: https://raw.githubusercontent.com/housefisharr/PMM-Configs/main/tv-awards.yml
    - url: https://raw.githubusercontent.com/housefisharr/PMM-Configs/main/tv-charts.yml
    - url: https://raw.githubusercontent.com/housefisharr/PMM-Configs/main/tv-networks.yml
    - url: https://raw.githubusercontent.com/housefisharr/PMM-Configs/main/collections-franchises.yml
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  assets_for_all: false
  sync_mode: sync
  show_unmanaged: false
  show_filtered: false
  show_missing: false
  save_missing: false
  run_again_delay: 2
  missing_only_released: false
  create_asset_folders: false
  delete_below_minimum: false
  tvdb_language: default
  show_missing_assets: true
  minimum_items: 1
  asset_depth: 0
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  default_collection_order:
  item_refresh_delay: 0
  delete_not_scheduled: false
  only_filter_missing: false
  show_options: false
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_users: all
  verify_ssl: true
  custom_repo:
  prioritize_assets: false
  playlist_report: true
  check_nightly: false
plex:
  url: 
  token: 
  timeout: 180
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:
  apikey: 
  language: en
  cache_expiration: 60
  region:
tautulli:
  url: 
  apikey: 
radarr:
  url: 
  token: 
  version: v3
  root_folder_path: /media/movies/1080p
  monitor: true
  availability: announced
  quality_profile: 1080p
  tag:
  search: true
  add_existing: false
  add_missing: false
  radarr_path:
  plex_path:
  upgrade_existing: false
sonarr:
  url: 
  token: 
  version: v3
  root_folder_path: /media/tv/1080p
  monitor: all
  quality_profile: 1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  add_existing: false
  add_missing: false
  sonarr_path:
  plex_path:
  upgrade_existing: false
trakt:
  client_id: 
  client_secret: 
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token: 
    token_type: 
    expires_in: 
    refresh_token: 
    scope: 
    created_at: 
